name: Github Action Build Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout

      - name: Build
        run: echo ${{ secrets.MY_MINE_SWEEPER_TOKEN }}
